# Generated by Django 6.0.3 on 2026-03-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='enable_sms_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
