# Generated by Django 6.0.3 on 2026-03-31 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shop_enable_sms_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='allow_staff_inventory_management',
            field=models.BooleanField(default=False),
        ),
    ]
