# Generated by Django 6.0.3 on 2026-03-10 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='model',
            new_name='product_model',
        ),
    ]
