"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""


import os
import sys
from os import environ
from pathlib import Path
from datetime import timedelta

import environ
from django.core.exceptions import ImproperlyConfigured

import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.celery import CeleryIntegration

try:
    import whitenoise  # noqa: F401
except ImportError:
    WHITENOISE_AVAILABLE = False
else:
    WHITENOISE_AVAILABLE = True

SENTRY_DSN = os.environ.get("SENTRY_DSN")

if SENTRY_DSN:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration(), CeleryIntegration()],
        traces_sample_rate=0.2,   # 20% of transactions — reduce noise
        send_default_pii=False    # Never send emails, IPs, cookies to Sentry (NDPR)
    )

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(DEBUG=(bool, False))
default_env_file = BASE_DIR / ".env"
if default_env_file.exists():
    environ.Env.read_env(default_env_file)

local_env_file = BASE_DIR / ".env.local"
if local_env_file.exists():
    environ.Env.read_env(local_env_file, overwrite=True)




# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

TESTING = "test" in sys.argv

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY", default=None)
if not SECRET_KEY:
    if TESTING:
        SECRET_KEY = "test-secret-key"
    else:
        raise ImproperlyConfigured("SECRET_KEY environment variable is required.")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["localhost", "127.0.0.1", "0.0.0.0"])


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'rest_framework_simplejwt.token_blacklist',
    
    # Local apps
    "apps.accounts",
    "apps.shops",
    "apps.inventory",
    "apps.sales",
    "apps.repairs",
    "apps.customers",
    "apps.reports",
    "apps.subscriptions",
    "apps.finance",
    "apps.notifications",
    "utils",
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'utils.middleware.SubscriptionMiddleware',  # Enforces active subscription
]

if WHITENOISE_AVAILABLE:
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": env.db("DATABASE_URL", default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}")
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Lagos'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"] if (BASE_DIR / "static").exists() else []
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = (
    "whitenoise.storage.CompressedManifestStaticFilesStorage"
    if WHITENOISE_AVAILABLE
    else "django.contrib.staticfiles.storage.StaticFilesStorage"
)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Authentication

AUTH_USER_MODEL = "accounts.CustomUser"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "utils.authentication.CookieJWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_PAGINATION_CLASS": "utils.exceptions.StandardPagination",
    "PAGE_SIZE": 20,
    # Only expose the interactive browser UI in development
    "DEFAULT_RENDERER_CLASSES": (
        ["rest_framework.renderers.JSONRenderer", "rest_framework.renderers.BrowsableAPIRenderer"]
        if DEBUG
        else ["rest_framework.renderers.JSONRenderer"]
    ),
    "EXCEPTION_HANDLER": "utils.exceptions.custom_exception_handler",
    # Rate limiting — protect login and all endpoints from brute force
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "30/minute",          # Unauthenticated (login, forgot-password)
        "user": "200/minute",         # Authenticated users
        "password_reset": "5/hour",   # Tight limit on forgot/reset-password (anti email-bomb)
    },
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

AUTH_COOKIE_ACCESS = env("AUTH_COOKIE_ACCESS", default="tracknfix_access")
AUTH_COOKIE_REFRESH = env("AUTH_COOKIE_REFRESH", default="tracknfix_refresh")
AUTH_COOKIE_SECURE = env.bool("AUTH_COOKIE_SECURE", default=False)
AUTH_COOKIE_SAMESITE = env("AUTH_COOKIE_SAMESITE", default="Lax")
AUTH_COOKIE_DOMAIN = env("AUTH_COOKIE_DOMAIN", default=None)
BOOTSTRAP_ADMIN_TOKEN = env("BOOTSTRAP_ADMIN_TOKEN", default="")
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = env("CSRF_COOKIE_SAMESITE", default="Lax")
SESSION_COOKIE_SAMESITE = env("SESSION_COOKIE_SAMESITE", default="Lax")
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[])
CSRF_COOKIE_SECURE = env("CSRF_COOKIE_SECURE", default="")
SESSION_COOKIE_SECURE = env("SESSION_COOKIE_SECURE", default="")


# NOTE: FRONTEND_URL and BACKEND_URL are declared below via env() — do not duplicate here.


#  Cors

CORS_ALLOWED_ORIGINS = env.list("CORS_ALLOWED_ORIGINS", default=[])
CORS_ALLOW_CREDENTIALS = True

#  Redis / Celery

REDIS_URL = env("REDIS_URL", default="redis://localhost:6379/0")
CELERY_BROKER_URL = env('REDIS_URL')
CELERY_RESULT_BACKEND = env('REDIS_URL')

# Only enable Redis SSL options when the configured URL actually uses rediss://.
# Local Docker and most local dev setups use plain redis:// and will crash if SSL
# parameters are forced onto a non-SSL connection.
if REDIS_URL.startswith("rediss://"):
    CELERY_REDIS_BACKEND_USE_SSL = {"ssl_cert_reqs": "none"}
    CELERY_BROKER_USE_SSL = {"ssl_cert_reqs": "none"}

#  Paystack

PAYSTACK_SECRET_KEY = env("PAYSTACK_SECRET_KEY", default="")
PAYSTACK_PUBLIC_KEY = env("PAYSTACK_PUBLIC_KEY", default="")
PAYSTACK_WEBHOOK_URL = env("PAYSTACK_WEBHOOK_URL", default="")

# App URLs — used in email links and Paystack callback redirect
BACKEND_URL = env("BACKEND_URL", default="http://127.0.0.1:8000")
FRONTEND_URL = env("FRONTEND_URL", default="http://localhost:5173")

# ── Celery ────────────────────────────────────────────────────────────────────
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "Africa/Lagos"

from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    # Check for expiring subscriptions every day at 9am Lagos time
    "notify-expiring-subscriptions": {
        "task": "apps.notifications.tasks.notify_expiring_subscriptions",
        "schedule": crontab(hour=9, minute=0),
    },
    # Send daily sales summary every morning at 8am
    "send-daily-summary": {
        "task": "apps.notifications.tasks.send_daily_summary",
        "schedule": crontab(hour=8, minute=0),
    },
}

# ── Email (console in dev, SMTP in prod) ─────────────────────────────────────
EMAIL_BACKEND = env("EMAIL_BACKEND", default="django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = env("EMAIL_HOST", default="smtp.gmail.com")
EMAIL_PORT = env.int("EMAIL_PORT", default=587)
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=True)
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="")

# ── SMS (Africa's Talking) ────────────────────────────────────────────────────
AT_API_KEY = env("AT_API_KEY", default="")
AT_USERNAME = env("AT_USERNAME", default="sandbox")  # Use 'sandbox' for free testing
AT_SENDER_ID = env("AT_SENDER_ID", default="")        # Optional: custom sender name


DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default="TRACKNFIX Inventory Management <noreply@tracknfix.com>")


# ── Production Security Headers ───────────────────────────────────────────────
# Only enable when USE_HTTPS=True in .env (your production server)
# Leave USE_HTTPS unset or False for local Docker development
USE_HTTPS = env.bool("USE_HTTPS", default=False)
# Default to Django-served media only in DEBUG. In non-debug deployments,
# enable this explicitly for local Docker or single-host setups that do not
# have Nginx/object storage handling media yet.
SERVE_MEDIA = env.bool("SERVE_MEDIA", default=DEBUG)
if not CSRF_TRUSTED_ORIGINS:
    csrf_defaults = {
        FRONTEND_URL.rstrip("/"),
        BACKEND_URL.rstrip("/"),
    }
    if not USE_HTTPS:
        csrf_defaults.update(
            {
                "http://localhost:3000",
                "http://127.0.0.1:3000",
                "http://localhost:5173",
                "http://127.0.0.1:5173",
                "http://localhost:8000",
                "http://127.0.0.1:8000",
            }
        )
    CSRF_TRUSTED_ORIGINS = sorted(origin for origin in csrf_defaults if origin)
if not CORS_ALLOWED_ORIGINS:
    cors_defaults = {
        FRONTEND_URL.rstrip("/"),
    }
    if not USE_HTTPS:
        cors_defaults.update(
            {
                "http://localhost:3000",
                "http://127.0.0.1:3000",
                "http://localhost:5173",
                "http://127.0.0.1:5173",
            }
        )
    CORS_ALLOWED_ORIGINS = sorted(origin for origin in cors_defaults if origin)
if not env("AUTH_COOKIE_SECURE", default="").strip():
    AUTH_COOKIE_SECURE = USE_HTTPS
if USE_HTTPS:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # Set to True ONLY if Nginx/proxy does NOT handle the HTTP→HTTPS redirect.
    # With Docker + Nginx, leave as False — Nginx handles it upstream.
    SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT", default=False)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"
else:
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

# ── Content Security Policy (mitigates XSS token theft) ──────────────────────
# Controls which scripts/resources browsers are allowed to load.
CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC  = ("'self'",)
CSP_STYLE_SRC   = ("'self'", "'unsafe-inline'")  # needed for inline styles common in React
CSP_IMG_SRC     = ("'self'", "data:", "blob:")      # local images + data URIs
CSP_FONT_SRC    = ("'self'", "https://fonts.gstatic.com")
CSP_CONNECT_SRC = ("'self'",)  # API calls — add your prod domain here when deploying
