# Generated by Django 6.0.3 on 2026-03-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_plan_features_plan_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='paystack_plan_code',
            field=models.CharField(blank=True, default='', max_length=100, null=True, unique=True),
        ),
    ]
