# Generated by Django 6.0.3 on 2026-03-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_amount_paid_sale_is_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='returned_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
