# Generated by Django 6.0.3 on 2026-04-07 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_sale_payments(apps, schema_editor):
    Sale = apps.get_model("sales", "Sale")
    SalePayment = apps.get_model("sales", "SalePayment")

    opening_payments = []
    for sale in Sale.objects.filter(amount_paid__gt=0).iterator(chunk_size=500):
        opening_payments.append(
            SalePayment(
                sale_id=sale.id,
                amount=sale.amount_paid,
                note="Opening payment imported from existing sale data",
                received_by_id=sale.staff_id,
                created_at=sale.created_at,
            )
        )

    if opening_payments:
        SalePayment.objects.bulk_create(opening_payments, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_saleitem_returned_quantity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SalePayment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField()),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sale_payments_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="sales.sale",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="salepayment",
            index=models.Index(fields=["created_at"], name="sales_salep_created_8ef013_idx"),
        ),
        migrations.AddIndex(
            model_name="salepayment",
            index=models.Index(fields=["sale", "created_at"], name="sales_salep_sale_id_716898_idx"),
        ),
        migrations.RunPython(backfill_sale_payments, migrations.RunPython.noop),
    ]
